version: '3'
services:
  nginx:
    image: nginx:alpine
    networks:
      - dev
    expose:
      - 443
    ports:
      - 9443:443
    volumes:
      - "./nginx:/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  app:
    image: tsrivishnu/for-rpi_alpine3.7_ruby:2.5.1
    networks:
      - dev
    environment:
      BUNDLE_PATH: "/app/.bundle"
    expose:
      - 4567
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app"
    command: 'bundle exec ruby app.rb'

networks:
  dev:
