version: '3'
services:
  app:
    image: forrpi/ruby:2.5.1_alpine3.7
    restart: always
    networks:
      - dev
    environment:
      BUNDLE_PATH: "/app/.bundle"
    expose:
      - 4567
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app"
    command: 'bundle exec ruby app.rb'

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16

