version: '3'
services:
  nginx:
    image: nginx:alpine
    networks:
      - dev
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx:/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  app:
    image: ruby:latest
    networks:
      - dev
    environment:
      BUNDLE_PATH: "/app/.bundle"
    expose:
      - 4567
    ports:
      - 9001:4567
    tty: true
    volumes:
      - ".:/app"
    working_dir: "/app"
    command: 'bundle exec ruby app.rb'

networks:
  dev:
